// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class Yacht
    {
        public Yacht()
        {
            Orders = new HashSet<Order>();
        }

        public int YachtId { get; set; }
        public string YachtName { get; set; }
        public string YachtType { get; set; }
        public int? RentalPrice { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}